In [7]:
import pandas as pd

# Define file path
file_path = "../data/raw/cdi_household_clean_nopii.dta"  # Adjust path as needed

# Load the .dta file
df = pd.read_stata(file_path, convert_categoricals=False)

# Display basic info
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1505 entries, 0 to 1504
Columns: 9565 entries, duration to time_wives
dtypes: datetime64[ns](45), float32(69), float64(8284), int16(1), int32(7), int8(344), object(815)
memory usage: 105.9+ MB

,duration,region,district,vill,village,community_type,restore_check,hhid_restore,village_restore,gender_restore,...,cocoa_sell_kg,cocoa_price_kg,farm_a_1_acres,farm_a_2_acres,farm_a_3_acres,farm_a_4_acres,farm_a_5_acres,total_landcleared_acres,time_hh,time_wives
0,7452,5,51,51024,Koitienko,RESTORE,1.0,0.0,,,...,1105.0,11.764706,4.942100,12.355250,NaN,NaN,NaN,NaN,127.699997,NaN
1,5408,4,41,41011,KLODIO,COMPARISON,NaN,NaN,,,...,NaN,NaN,1.235525,12.355250,2.47105,NaN,NaN,NaN,88.000000,NaN
2,6208,5,51,51028,Ananguié,RESTORE,0.0,NaN,,,...,212.5,1000.000000,4.942100,NaN,NaN,NaN,NaN,NaN,102.650002,NaN
3,3228,7,74,74003,BOHOUIN,COMPARISON,NaN,NaN,,,...,NaN,NaN,2.471050,NaN,NaN,NaN,NaN,NaN,57.183334,NaN
4,8314,4,41,41011,KLODIO,COMPARISON,NaN,NaN,,,...,NaN,NaN,42.007851,51.892052,NaN,NaN,NaN,NaN,143.449997,58.316666

In [8]:
# Count missing values per column
df.isnull().sum().sort_values(ascending=False)

shade_alivenow_1_16     1504
shadetree_index_1_17    1504
shadetree_calc_1_17     1504
shade_tree_tot_1_17     1504
shade_natural_1_17      1504
                        ...
lead_vill_11               0
lead_vill_12               0
lead_vill_13               0
lead_vill_97               0
consent_record             0
Length: 9565, dtype: int64

In [9]:
df.describe()

,duration,region,district,vill,restore_check,hhid_restore,confirm_restore,any_questions,consent,consent_record,...,cocoa_sell_kg,cocoa_price_kg,farm_a_1_acres,farm_a_2_acres,farm_a_3_acres,farm_a_4_acres,farm_a_5_acres,total_landcleared_acres,time_hh,time_wives
count,1505.000000,1505.000000,1505.000000,1505.000000,738.000000,410.000000,410.0,1505.000000,1505.0,1505.000000,...,8.230000e+02,823.000000,1505.000000,975.000000,443.000000,174.000000,79.000000,204.000000,1503.000000,502.000000
mean,6957.524252,5.161462,53.061130,52846.528239,0.555556,50830.239024,1.0,0.360133,1.0,0.985382,...,2.395653e+03,814.879883,11.295180,12.340106,17.208073,6.365794,5.378443,1.944362,143.681305,71.983437
min,1631.000000,4.000000,41.000000,41001.000000,0.000000,0.000000,1.0,0.000000,1.0,0.000000,...,0.000000e+00,0.042857,0.617763,0.617763,0.000000,0.000000,0.617763,0.000000,0.683333,4.566667
25%,5208.000000,4.000000,41.000000,41028.000000,0.000000,50454.250000,1.0,0.000000,1.0,1.000000,...,2.800000e+02,850.000000,4.942100,2.471050,2.471050,2.471050,1.235525,1.235525,85.750000,43.833332
50%,6497.000000,5.000000,51.000000,51023.000000,1.000000,50964.000000,1.0,0.000000,1.0,1.000000,...,5.400000e+02,1000.000000,7.413150,4.942100,4.942100,4.942100,2.471050,1.235525,109.183334,57.166668
75%,8233.000000,6.000000,62.000000,54002.000000,1.000000,51403.750000,1.0,1.000000,1.0,1.000000,...,1.040000e+03,1000.000000,12.355250,8.648675,7.413150,7.413150,7.413150,2.471050,141.975006,77.195831
max,28332.000000,7.000000,76.000000,75001.000000,1.000000,51847.000000,1.0,1.000000,1.0,1.000000,...,1.200000e+06,12000.000000,190.270844,4947.041992,4996.462891,65.482826,24.710501,14.826300,9561.250000,1506.116699
std,2653.697025,1.102995,11.557741,11324.051792,0.497241,2571.958581,0.0,0.480198,0.0,0.120058,...,4.183907e+04,551.531799,12.099500,158.433426,237.193359,8.251189,5.829566,1.598416,294.980865,96.617920

In [10]:
for col in df.columns:
    if df[col].dtype == 'object':  # Text-based columns
        print(f"{col}: {df[col].nunique()} unique values")

village: 103 unique values
community_type: 2 unique values
village_restore: 40 unique values
gender_restore: 3 unique values
sample_restore: 3 unique values
hhid_nonrestore: 1505 unique values
hhid: 1505 unique values
audio_audit: 381 unique values
nothead_oth: 28 unique values
ethnicity_oth: 19 unique values
language_oth: 130 unique values
lead_vill: 42 unique values
lead_villo: 96 unique values
hh_relate_oth_1: 2 unique values
ethnicity_head_oth_1: 17 unique values
hhmem_edu_levelo_1: 5 unique values
hhmem_edu_whyno_oth_1: 3 unique values
illness_1: 172 unique values
illness_oth_1: 153 unique values
care_1: 53 unique values
care_oth_1: 7 unique values
hh_relate_oth_2: 9 unique values
hhmem_edu_whyno_2: 17 unique values
hhmem_edu_whyno_oth_2: 14 unique values
illness_2: 154 unique values
illness_oth_2: 138 unique values
care_2: 36 unique values
care_oth_2: 6 unique values
hh_relate_oth_3: 27 unique values
hhmem_edu_levelo_3: 2 unique values
hhmem_edu_whyno_3: 22 unique values
hhmem_edu_whyno_oth_3: 42 unique values
illness_3: 118 unique values
illness_oth_3: 107 unique values
care_3: 35 unique values
care_oth_3: 5 unique values
hh_relate_oth_4: 13 unique values
hhmem_edu_levelo_4: 3 unique values
hhmem_edu_whyno_4: 22 unique values
hhmem_edu_whyno_oth_4: 42 unique values
illness_4: 103 unique values
illness_oth_4: 62 unique values
care_4: 31 unique values
care_oth_4: 5 unique values
hh_relate_oth_5: 18 unique values
hhmem_edu_levelo_5: 2 unique values
hhmem_edu_whyno_5: 20 unique values
hhmem_edu_whyno_oth_5: 39 unique values
illness_5: 75 unique values
illness_oth_5: 56 unique values
care_5: 29 unique values
care_oth_5: 2 unique values
hh_relate_oth_6: 15 unique values
hhmem_edu_levelo_6: 4 unique values
hhmem_edu_whyno_6: 19 unique values
hhmem_edu_whyno_oth_6: 29 unique values
illness_6: 70 unique values
illness_oth_6: 48 unique values
care_6: 27 unique values
care_oth_6: 2 unique values
hh_relate_oth_7: 15 unique values
hhmem_edu_levelo_7: 2 unique values
hhmem_edu_whyno_7: 16 unique values
hhmem_edu_whyno_oth_7: 19 unique values
illness_7: 65 unique values
illness_oth_7: 29 unique values
care_7: 26 unique values
care_oth_7: 2 unique values
hh_relate_oth_8: 10 unique values
hhmem_edu_levelo_8: 2 unique values
hhmem_edu_whyno_8: 11 unique values
hhmem_edu_whyno_oth_8: 13 unique values
illness_8: 55 unique values
illness_oth_8: 25 unique values
care_8: 25 unique values
care_oth_8: 3 unique values
hh_relate_oth_9: 7 unique values
hhmem_edu_levelo_9: 2 unique values
hhmem_edu_whyno_9: 11 unique values
hhmem_edu_whyno_oth_9: 8 unique values
illness_9: 43 unique values
illness_oth_9: 14 unique values
care_9: 18 unique values
care_oth_9: 2 unique values
hh_relate_oth_10: 6 unique values
hhmem_edu_levelo_10: 3 unique values
hhmem_edu_whyno_10: 8 unique values
hhmem_edu_whyno_oth_10: 9 unique values
illness_10: 33 unique values
illness_oth_10: 12 unique values
care_10: 15 unique values
care_oth_10: 2 unique values
hh_relate_oth_11: 6 unique values
hhmem_edu_whyno_11: 8 unique values
hhmem_edu_whyno_oth_11: 4 unique values
illness_11: 29 unique values
illness_oth_11: 5 unique values
care_11: 19 unique values
care_oth_11: 2 unique values
hh_relate_oth_12: 4 unique values
hhmem_edu_whyno_oth_12: 4 unique values
illness_12: 27 unique values
illness_oth_12: 7 unique values
care_12: 12 unique values
care_oth_12: 2 unique values
hh_relate_oth_13: 4 unique values
hhmem_edu_whyno_oth_13: 3 unique values
illness_13: 13 unique values
illness_oth_13: 4 unique values
care_13: 9 unique values
care_oth_13: 2 unique values
hh_relate_oth_14: 2 unique values
hhmem_edu_whyno_oth_14: 3 unique values
illness_14: 12 unique values
illness_oth_14: 6 unique values
care_14: 8 unique values
care_oth_14: 2 unique values
hh_relate_oth_15: 2 unique values
hhmem_edu_whyno_oth_15: 2 unique values
illness_15: 11 unique values
illness_oth_15: 4 unique values
care_15: 7 unique values
hhmem1: 1500 unique values
hhmem2: 1461 unique values
hhmem3: 1406 unique values
hhmem4: 1300 unique values
hhmem5: 1088 unique values
hhmem6: 879 unique values
hhmem7: 666 unique values
hhmem8: 470 unique values
hhmem9: 330 unique values
hhmem10: 234 unique values
hhmem11: 163 unique values
hhmem12: 130 unique values
hhmem13: 85 unique values
hhmem14: 64 unique values
hhmem15: 48 unique values
unitarea: 3 unique values
cocoa_unit: 2 unique values
cocoa_buyer: 6 unique values
cocoa_buyero: 246 unique values
cocoa_howinc: 12 unique values
cocoa_howinc_oth: 3 unique values
cocoa_howdec: 10 unique values
cocoa_howdec_oth: 53 unique values
input_ngo: 10 unique values
input_pc: 20 unique values
farm_owner_1: 35 unique values
lose_access_who_oth_1: 3 unique values
lose_access_why_oth_1: 2 unique values
abunu_sc_ob_1: 110 unique values
farm_decrights_1: 13 unique values
farm_decrights_oth_1: 20 unique values
cocoa_variety_1: 24 unique values
cocoa_variety_oth_1: 52 unique values
cocoa_labor_oth_1: 89 unique values
crop_type_1: 530 unique values
crop_type_oth_1: 40 unique values
noncocoa_whyno_1: 23 unique values
noncocoa_whyno_oth_1: 63 unique values
noncocoa_species_1: 358 unique values
noncocoa_species_oth_1: 157 unique values
shadetree_1: 627 unique values
shadetree_oth_1: 165 unique values
shadetree_label_1_1: 31 unique values
shadetree_label_1_2: 31 unique values
shadetree_label_1_3: 30 unique values
shadetree_label_1_4: 29 unique values
shadetree_label_1_5: 21 unique values
shadetree_label_1_6: 20 unique values
shadetree_label_1_7: 17 unique values
shadetree_label_1_8: 15 unique values
shadetree_label_1_9: 13 unique values
shadetree_label_1_10: 12 unique values
shadetree_label_1_11: 10 unique values
shadetree_label_1_12: 9 unique values
shadetree_label_1_13: 6 unique values
shadetree_label_1_14: 4 unique values
shadetree_label_1_15: 4 unique values
shadetree_label_1_16: 3 unique values
shadetree_label_1_17: 2 unique values
shadetree_label_1_18: 2 unique values
labor_activ_1: 44 unique values
labor_activ_oth_1: 15 unique values
labor_hh_1: 60 unique values
fam_worker_1: 104 unique values
fam_worker_label_1_1: 1374 unique values
fam_worker_label_1_2: 720 unique values
fam_worker_label_1_3: 276 unique values
fam_worker_label_1_4: 127 unique values
fam_worker_label_1_5: 46 unique values
fam_worker_label_1_6: 16 unique values
fam_worker_label_1_7: 5 unique values
fam_worker_label_1_8: 3 unique values
disease_1: 16 unique values
disease_oth_1: 40 unique values
disease_label_1_1: 8 unique values
disease_year_1_1: 8 unique values
disease_label_1_2: 4 unique values
disease_year_1_2: 8 unique values
disease_label_1_3: 3 unique values
disease_year_1_3: 7 unique values
pest_1: 87 unique values
pest_oth_1: 30 unique values
replant_finance_1: 16 unique values
replant_finance_oth_1: 9 unique values
replant_rehab_prgm_1: 4 unique values
replant_rehab_prgm_oth_1: 5 unique values
replant_rsn_not_1: 21 unique values
doc_land_list_1: 29 unique values
doc_land_list_oth_1: 27 unique values
land_title_1: 15 unique values
land_title_oth_1: 273 unique values
doc_land_cocoa_hhm_1: 13 unique values
cut_permission_prs_1: 17 unique values
cut_permission_prs_oth_1: 10 unique values
worry_reason_1: 26 unique values
worry_reason_oth_1: 18 unique values
conflict_type_oth_1_1: 3 unique values
conflict_landwho_oth_1_1: 4 unique values
conflict_resolvewho_1_1: 25 unique values
conflict_resolvewho_oth_1_1: 2 unique values
conflict_type_oth_1_2: 2 unique values
conflict_landwho_oth_1_2: 2 unique values
conflict_resolvewho_1_2: 11 unique values
conflict_resolvewho_oth_1_2: 2 unique values
conflict_resolvewho_1_3: 3 unique values
farm_use_oth_2: 3 unique values
farm_owner_2: 26 unique values
lose_access_who_oth_2: 3 unique values
abunu_sc_ob_2: 34 unique values
farm_decrights_2: 12 unique values
farm_decrights_oth_2: 11 unique values
cocoa_variety_2: 13 unique values
cocoa_variety_oth_2: 12 unique values
cocoa_labor_oth_2: 34 unique values
crop_type_2: 229 unique values
crop_type_oth_2: 25 unique values
noncocoa_whyno_2: 23 unique values
noncocoa_whyno_oth_2: 211 unique values
noncocoa_species_2: 132 unique values
noncocoa_species_oth_2: 62 unique values
shadetree_2: 171 unique values
shadetree_oth_2: 58 unique values
shadetree_label_2_1: 22 unique values
shadetree_label_2_2: 24 unique values
shadetree_label_2_3: 20 unique values
shadetree_label_2_4: 15 unique values
shadetree_label_2_5: 14 unique values
shadetree_label_2_6: 12 unique values
shadetree_label_2_7: 7 unique values
shadetree_label_2_8: 4 unique values
shadetree_label_2_9: 2 unique values
shadetree_label_2_10: 2 unique values
labor_activ_2: 27 unique values
labor_activ_oth_2: 3 unique values
labor_hh_2: 48 unique values
fam_worker_2: 55 unique values
fam_worker_label_2_1: 390 unique values
fam_worker_label_2_2: 194 unique values
fam_worker_label_2_3: 78 unique values
fam_worker_label_2_4: 30 unique values
fam_worker_label_2_5: 11 unique values
fam_worker_label_2_6: 3 unique values
fam_worker_label_2_7: 3 unique values
disease_2: 14 unique values
disease_oth_2: 16 unique values
disease_label_2_1: 7 unique values
disease_year_2_1: 8 unique values
disease_label_2_2: 4 unique values
disease_year_2_2: 7 unique values
disease_label_2_3: 2 unique values
disease_year_2_3: 3 unique values
pest_2: 56 unique values
pest_oth_2: 8 unique values
replant_finance_2: 10 unique values
replant_finance_oth_2: 3 unique values
replant_rehab_prgm_oth_2: 2 unique values
replant_rsn_not_2: 14 unique values
doc_land_list_2: 20 unique values
doc_land_list_oth_2: 14 unique values
land_title_2: 17 unique values
land_title_oth_2: 201 unique values
doc_land_cocoa_hhm_2: 9 unique values
cut_permission_prs_2: 11 unique values
cut_permission_prs_oth_2: 5 unique values
worry_reason_2: 17 unique values
worry_reason_oth_2: 13 unique values
conflict_type_oth_2_1: 2 unique values
conflict_landwho_oth_2_1: 2 unique values
conflict_resolvewho_2_1: 11 unique values
conflict_resolvewho_oth_2_1: 3 unique values
conflict_landwho_oth_2_2: 2 unique values
conflict_resolvewho_2_2: 3 unique values
farm_use_oth_3: 3 unique values
farm_owner_3: 15 unique values
lose_access_who_oth_3: 4 unique values
lose_access_why_oth_3: 4 unique values
abunu_sc_ob_3: 9 unique values
farm_decrights_3: 11 unique values
farm_decrights_oth_3: 4 unique values
cocoa_variety_3: 14 unique values
cocoa_variety_oth_3: 4 unique values
cocoa_labor_oth_3: 11 unique values
crop_type_3: 73 unique values
crop_type_oth_3: 12 unique values
noncocoa_whyno_3: 17 unique values
noncocoa_whyno_oth_3: 142 unique values
noncocoa_species_3: 44 unique values
noncocoa_species_oth_3: 38 unique values
shadetree_3: 42 unique values
shadetree_oth_3: 18 unique values
shadetree_label_3_1: 12 unique values
shadetree_label_3_2: 14 unique values
shadetree_label_3_3: 13 unique values
shadetree_label_3_4: 8 unique values
shadetree_label_3_5: 6 unique values
shadetree_label_3_6: 5 unique values
shadetree_label_3_7: 3 unique values
shadetree_label_3_8: 3 unique values
shadetree_label_3_9: 2 unique values
shadetree_label_3_10: 2 unique values
labor_activ_3: 13 unique values
labor_hh_3: 24 unique values
fam_worker_3: 23 unique values
fam_worker_label_3_1: 78 unique values
fam_worker_label_3_2: 35 unique values
fam_worker_label_3_3: 17 unique values
fam_worker_label_3_4: 8 unique values
fam_worker_label_3_5: 5 unique values
disease_3: 8 unique values
disease_label_3_1: 6 unique values
disease_year_3_1: 7 unique values
disease_label_3_2: 3 unique values
disease_year_3_2: 4 unique values
pest_3: 26 unique values
pest_oth_3: 4 unique values
replant_rsn_not_3: 8 unique values
doc_land_list_3: 16 unique values
doc_land_list_oth_3: 9 unique values
land_title_3: 13 unique values
land_title_oth_3: 80 unique values
doc_land_cocoa_hhm_3: 8 unique values
cut_permission_prs_3: 9 unique values
worry_reason_3: 10 unique values
worry_reason_oth_3: 5 unique values
conflict_type_oth_3_1: 2 unique values
conflict_landwho_oth_3_1: 3 unique values
conflict_resolvewho_3_1: 5 unique values
farm_use_oth_4: 3 unique values
farm_owner_4: 12 unique values
abunu_sc_ob_4: 8 unique values
farm_decrights_4: 11 unique values
farm_decrights_oth_4: 2 unique values
cocoa_variety_4: 8 unique values
cocoa_variety_oth_4: 3 unique values
cocoa_labor_oth_4: 8 unique values
crop_type_4: 33 unique values
crop_type_oth_4: 5 unique values
noncocoa_whyno_4: 10 unique values
noncocoa_whyno_oth_4: 61 unique values
noncocoa_species_4: 21 unique values
noncocoa_species_oth_4: 15 unique values
shadetree_4: 12 unique values
shadetree_oth_4: 9 unique values
shadetree_label_4_1: 8 unique values
shadetree_label_4_2: 7 unique values
shadetree_label_4_3: 6 unique values
shadetree_label_4_4: 6 unique values
shadetree_label_4_5: 3 unique values
shadetree_label_4_6: 2 unique values
shadetree_label_4_7: 2 unique values
shadetree_label_4_8: 2 unique values
shadetree_label_4_9: 2 unique values
labor_activ_4: 10 unique values
labor_hh_4: 12 unique values
fam_worker_4: 9 unique values
fam_worker_label_4_1: 24 unique values
fam_worker_label_4_2: 12 unique values
fam_worker_label_4_3: 6 unique values
fam_worker_label_4_4: 2 unique values
fam_worker_label_4_5: 2 unique values
fam_worker_label_4_6: 2 unique values
disease_4: 7 unique values
disease_label_4_1: 5 unique values
disease_year_4_1: 6 unique values
disease_label_4_2: 3 unique values
disease_year_4_2: 2 unique values
pest_4: 15 unique values
replant_rsn_not_4: 6 unique values
doc_land_list_4: 13 unique values
doc_land_list_oth_4: 3 unique values
land_title_4: 11 unique values
land_title_oth_4: 33 unique values
doc_land_cocoa_hhm_4: 6 unique values
cut_permission_prs_4: 6 unique values
worry_reason_4: 6 unique values
worry_reason_oth_4: 3 unique values
conflict_type_oth_4_1: 2 unique values
conflict_resolvewho_4_1: 4 unique values
conflict_resolvewho_oth_4_1: 2 unique values
conflict_resolvewho_4_2: 2 unique values
farm_owner_5: 9 unique values
abunu_sc_ob_5: 2 unique values
farm_decrights_5: 6 unique values
cocoa_variety_oth_5: 2 unique values
cocoa_labor_oth_5: 2 unique values
crop_type_5: 17 unique values
crop_type_oth_5: 2 unique values
noncocoa_whyno_5: 7 unique values
noncocoa_whyno_oth_5: 29 unique values
noncocoa_species_5: 8 unique values
noncocoa_species_oth_5: 9 unique values
shadetree_5: 4 unique values
shadetree_label_5_1: 3 unique values
shadetree_label_5_2: 3 unique values
shadetree_label_5_3: 3 unique values
labor_activ_5: 4 unique values
labor_hh_5: 5 unique values
fam_worker_5: 6 unique values
fam_worker_label_5_1: 7 unique values
fam_worker_label_5_2: 6 unique values
fam_worker_label_5_3: 3 unique values
fam_worker_label_5_4: 2 unique values
disease_label_5_1: 4 unique values
disease_year_5_1: 4 unique values
pest_5: 6 unique values
doc_land_list_5: 11 unique values
doc_land_list_oth_5: 3 unique values
land_title_5: 6 unique values
land_title_oth_5: 18 unique values
doc_land_cocoa_hhm_5: 6 unique values
worry_reason_oth_5: 2 unique values
lose_access2_who: 9 unique values
lose_access2_why: 9 unique values
challenge_main: 279 unique values
challenge_main_oth: 148 unique values
challenge_reason1: 83 unique values
challenge_reason1_oth: 82 unique values
noncocoa_benlist: 304 unique values
noncocoa_benlist_oth: 47 unique values
noncocoa_affecthow: 70 unique values
noncocoa_affecthow_oth: 5 unique values
motivate_plant: 126 unique values
motivate_plant_oth: 72 unique values
motivate_maintain: 126 unique values
motivate_maintain_oth: 45 unique values
shade_why1_oth: 79 unique values
shade_benefit: 386 unique values
shade_benefit_oth: 19 unique values
shade_futurebenefit: 433 unique values
shade_futurebenefit_oth: 22 unique values
farmercoop: 7 unique values
comsvc: 35 unique values
comsvc_ben: 25 unique values
comsvc_gov_oth: 8 unique values
comsvc_ngo_oth: 12 unique values
comaco_nowhy: 9 unique values
comaco_nowhy_oth: 51 unique values
training_whom: 35 unique values
training_whom_oth: 74 unique values
income_source: 85 unique values
clear_forest_type: 4 unique values
clear_who_oth: 9 unique values
clear_reas_oth: 9 unique values
foresttype: 8 unique values
forest_label_1: 4 unique values
cf_nonharvben_1: 121 unique values
cf_nonharvben_oth_1: 15 unique values
forest_hhs_1: 452 unique values
forest_ca_1: 294 unique values
ftreedied_species_1: 229 unique values
ftreedied_species_oth_1: 131 unique values
ftreenew_species_1: 70 unique values
ftreenew_species_oth_1: 30 unique values
fwildlifedied_1: 76 unique values
fwildlifedied_oth_1: 73 unique values
fwlife_newtypes_1: 32 unique values
fwlife_newtypes_oth_1: 9 unique values
noaccwhy_1: 18 unique values
noaccwhy_oth_1: 5 unique values
noaccimpact_1: 43 unique values
noaccimpact_oth_1: 2 unique values
forstrict_who_1: 22 unique values
forstrict_who_oth_1: 2 unique values
rules_whoenforce_1: 100 unique values
rules_violate_1: 32 unique values
fclear_who_1: 16 unique values
fclear_who_oth_1: 19 unique values
forestore_activity_1: 10 unique values
forest_label_2: 3 unique values
cf_nonharvben_2: 25 unique values
forest_hhs_2: 38 unique values
forest_ca_2: 22 unique values
ftreedied_species_2: 20 unique values
ftreedied_species_oth_2: 14 unique values
ftreenew_species_2: 7 unique values
ftreenew_species_oth_2: 3 unique values
fwildlifedied_2: 15 unique values
noaccwhy_2: 4 unique values
noaccimpact_2: 3 unique values
forstrict_who_2: 5 unique values
rules_whoenforce_2: 12 unique values
rules_violate_2: 9 unique values
fclear_who_2: 6 unique values
forest_label_3: 2 unique values
cf_nonharvben_3: 3 unique values
noaccwhy_3: 2 unique values
rules_whoenforce_3: 3 unique values
rules_violate_3: 3 unique values
interest2_1: 2 unique values
title2_1: 2 unique values
monitor2_1: 2 unique values
interest3_1: 2 unique values
title3_1: 2 unique values
monitor3_1: 3 unique values
interest2_2: 3 unique values
title2_2: 3 unique values
monitor2_2: 3 unique values
interest3_2: 3 unique values
title3_2: 3 unique values
monitor3_2: 3 unique values
interest2_3: 3 unique values
title2_3: 3 unique values
monitor2_3: 3 unique values
interest3_3: 3 unique values
title3_3: 3 unique values
monitor3_3: 3 unique values
interest2_l: 2 unique values
title2_l: 2 unique values
monitor2_l: 2 unique values
interest3_l: 2 unique values
title3_l: 2 unique values
monitor3_l: 3 unique values
presence1_1: 2 unique values
treesland1_1: 2 unique values
presence2_1: 2 unique values
treesland2_1: 2 unique values
presence1_l: 2 unique values
treesland1_l: 2 unique values
presence2_l: 2 unique values
treesland2_l: 2 unique values
forest_randa_1: 3 unique values
health_randa_1: 3 unique values
school_randa_1: 3 unique values
econ_randa_1: 3 unique values
forest_randb_1: 3 unique values
health_randb_1: 3 unique values
school_randb_1: 3 unique values
econ_randb_1: 3 unique values
forest_randa_2: 4 unique values
health_randa_2: 3 unique values
school_randa_2: 3 unique values
econ_randa_2: 3 unique values
forest_randb_2: 3 unique values
health_randb_2: 4 unique values
school_randb_2: 4 unique values
econ_randb_2: 4 unique values
forest_randa_l: 3 unique values
health_randa_l: 3 unique values
school_randa_l: 3 unique values
econ_randa_l: 3 unique values
forest_randb_l: 3 unique values
health_randb_l: 3 unique values
school_randb_l: 3 unique values
econ_randb_l: 3 unique values
roof_oth: 8 unique values
wall_oth: 13 unique values
toilet_oth: 17 unique values
landmark: 1314 unique values
farm_image: 1505 unique values
int_lang_oth: 27 unique values
instancename: 1505 unique values
key: 1505 unique values
meta1instancename: 2 unique values
w_village: 103 unique values
w_community_type: 3 unique values
w_hhid2: 501 unique values
w_hh_name_1: 502 unique values
w_hh_name_2: 502 unique values
w_hh_name_3: 499 unique values
w_hh_name_4: 477 unique values
w_hh_name_5: 401 unique values
w_hh_name_6: 335 unique values
w_hh_name_7: 245 unique values
w_hh_name_8: 175 unique values
w_hh_name_9: 122 unique values
w_hh_name_10: 77 unique values
w_hh_name_11: 52 unique values
w_hh_name_12: 43 unique values
w_hh_name_13: 29 unique values
w_hh_name_14: 22 unique values